### ISSUE TITLE
Your previous login was expired.

### ISSUE THREAD

**Issue by DavidePajot** [sumithemmadi/truecallerpy#10]
I always get "_Your previous login was expired_" even though I log in successfully

`C:\Users\user>truecallerpy --login -f C:\Users\user\Desktop\file.json`
Your installationId : 00000--000000000000000000000000000000000000000000000000000000000
Logged in successfully.

`C:\Users\user>truecallerpy -s [number]`
Your previous login was expired.
Please login to your account

`C:\Users\user>`

**Comment by sumithemmadi** [comment]
That installationId is expired.
Login with phone number or try to copy the json file after login into Truecaller app and use that json file to login.

**Comment by DavidePajot** [comment]
I have already tried, if I try to log in manually I get "KeyError: parsedPhoneNumber" I enter the number like this: +391233456789

**Comment by DavidePajot** [comment]
This is my personal number preceded by +39, what's wrong with that?

![Immagine](https://user-images.githubusercontent.com/12814138/196731528-d5da9c16-a68c-4c78-a9d5-5ec7424c8662.png)

**Comment by DavidePajot** [comment]
I tried with truecallerjs and what I got was "Request failed with status code 451", I think it can help you.

**Comment by sumithemmadi** [comment]
The number you have entered is not a valid number.

**Comment by sumithemmadi** [comment]
Resolved your issue https://github.com/sumithemmadi/truecallerpy/commits/v0.1.2
