### ISSUE TITLE
Is there any limitations?

### ISSUE THREAD

**Issue by Denver1997** [sumithemmadi/truecallerpy#11]
Is there any limitations for check numbers?

**Comment by sumithemmadi** [comment]
Yes there is a limit.
You can use bulk search

**Comment by Denver1997** [comment]
How many numbers search at bulk from 1 login?

**Comment by sumithemmadi** [comment]
Per request it would be  around 30 numbers  and and 5 to 6 requests per day 
But once I have searched 100 phone numbers 
![QLVp7A2W jpg_medium](https://user-images.githubusercontent.com/50250422/208607041-b37798a9-e66e-4e41-8773-fc6443ec40cf.jpg)

**Comment by Sentientech** [comment]
So (30 requests) x (5 requests per day) = (150 numbers per day)
