### ISSUE TITLE
429 Error

### ISSUE THREAD

**Issue by CALCULUSDEVELOPER** [sumithemmadi/truecallerpy#12]
How to fix 429 error??

**Comment by sumithemmadi** [comment]
You are rate limited

**Comment by Sentientech** [comment]
How many requests per what time duration?

**Comment by sumithemmadi** [comment]
1. **Normal search** : 50 - 70 numbers per day for 
2. **Bulk Search** : 30 numbers per request and 5 - 6 requests per day
