### ISSUE TITLE
Having this weird issue in django application

### ISSUE THREAD

**Issue by 833M0L3** [sumithemmadi/truecallerpy#14]
Whenever I import truecallerpy in any of my Django projects python files, I can't run the manage.py runserver command, as somehow truecallerpy gets in the middle to be executed instead.

For example : 
Here I have imported truecallerpy in views.py of Django application 
![image](https://github.com/sumithemmadi/truecallerpy/assets/59522309/d1ecfddd-4863-4de6-b321-f8bb7c2c31df)

When I try to run the server, it shows truecallerpy arguments error.
![image](https://github.com/sumithemmadi/truecallerpy/assets/59522309/287471b7-83ad-4db7-a5fc-70cbc6541723)

**Comment by Vinayak-SP** [comment]
> Whenever I import truecallerpy in any of my Django projects python files, I can't run the manage.py runserver command, as somehow truecallerpy gets in the middle to be executed instead.
> 
> For example : Here I have imported truecallerpy in views.py of Django application ![image](https://user-images.githubusercontent.com/59522309/237865027-d1ecfddd-4863-4de6-b321-f8bb7c2c31df.png)
> 
> When I try to run the server, it shows truecallerpy arguments error. ![image](https://user-images.githubusercontent.com/59522309/237865323-287471b7-83ad-4db7-a5fc-70cbc6541723.png)

I'm unable to import, shows truecallerpy is unresolved even though I have installed truecallerpy.
How did you imported it ?

**Comment by sumithemmadi** [comment]
I haven't updated this  package from a long time. 

Wait for next update , I will fix some bugs and add some features

**Comment by sumithemmadi** [comment]
use [truecallerpy@1.0.2](https://pypi.org/project/truecallerpy/)
