### ISSUE TITLE
how to remove installationId

### ISSUE THREAD

**Issue by ashenindeewara** [sumithemmadi/truecallerpy#17]

**Comment by sumithemmadi** [comment]
Locate the home directory on either Linux or Windows, navigate to the folder named `.config`. Within the `.config` folder, delete the directories named `truecallerpy` and `truecallerjs`( if you are using  `truecallerjs` npm package).

For Linux:
```bash
rm -rf ~/.config/truecallerpy
rm -rf ~/.config/truecallerjs
```

For Windows (using PowerShell):
```powershell
Remove-Item -Recurse -Force -Path $HOMEPATH/.config/truecallerpy
Remove-Item -Recurse -Force -Path $HOMEPATH/.config/truecallerjs
```

These commands will delete the `truecallerpy` and `truecallerjs` folders, along with `authkey.json` which contains `InstallationId`
