### ISSUE TITLE
login expired

### ISSUE THREAD

**Issue by nedbaker12** [sumithemmadi/truecallerpy#19]
"Your previous login was expired. 
Please login to your account "
is there a way to auto update id without login. how long the id usually work? when does it expire. is there a way to get a permanent id without login ?

**Comment by sumithemmadi** [comment]
Thank you for the clarification. Based on the updated information, here's the revised version with proper grammar:

The InstallationId remains valid until another login occurs. Once another login happens, the previous InstallationId associated with the  will expire, and users will need to re-login with their phone number to generate a new key.

Please take note of the following limitations when using the tool:

**Maximum Number of Phone Numbers**: The tool supports searching for 30 or fewer phone numbers at once in a single request. If you exceed this limit, you may need to split your input into multiple requests.

**Formatting**: Ensure that the phone numbers are correctly formatted and do not contain any additional characters or spaces. The tool expects the phone numbers to be provided in a comma-separated format.

**Comment by nedbaker12** [comment]
i have not done any login after i created the installationID with my number and now i used the same login ID after a week now. its showing login expired. any reason this might happened?
