### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Destroyer40** [sumithemmadi/truecallerpy#20]
> I got this error when I search for a number name 

 _PS C:\Users\AppData\Roaming\Python\Python312\Scripts>_ `.\truecallerpy -s 0123456789 --name`

### output:** Expecting value: line 1 column 1 (char 0)**

_PS C:\Users\AppData\Roaming\Python\Python312\Scripts>_` .\truecallerpy.exe -s 0123456789`

**output:###  Expecting value: line 1 column 1 (char 0)**

**Comment by sumithemmadi** [comment]
There is an issue with the virtual environment of Python. The error occurs when I use the virtual environment, but it works fine outside of it. I will resolve this error as soon as possible.

**Comment by Legend-Mukund** [comment]
@sumithemmadi Bruh this error is even raising without any virtual enviornment

**Comment by VICIWUOHA** [comment]
@sumithemmadi  This Error happens when the API returns a 429 response probably when many previous successful calls have been made.

It is a result of the response not being an actual dictionary in this Line [search.py#L39](https://github.com/sumithemmadi/truecallerpy/blob/83a39ebea51b00a7b1ef38f6963c818954d7e745/truecallerpy/search.py#L39).
Encountered it today.

**Comment by demiceOP** [comment]
> @sumithemmadi This Error happens when the API returns a 429 response probably when many previous successful calls have been made.
> 
> It is a result of the response not being an actual dictionary in this Line [search.py#L39](https://github.com/sumithemmadi/truecallerpy/blob/83a39ebea51b00a7b1ef38f6963c818954d7e745/truecallerpy/search.py#L39). Encountered it today.

Got any fix for that?

**Comment by VICIWUOHA** [comment]
Sure. @sumithemmadi, we can add a line `response.raise_for_status()` before returning the response.json(), this way if a non 200 response is received from the API, we would get a clearer error trace. 

The solution as at now if you're using this would be to wait for about 24hrs before you'd be able to use the installation_id again. 
Hope. This helps @demiceOP. 

We can open a PR for that one-liner.

**Comment by sumithemmadi** [comment]
@Destroyer40 your issue is fix in [Truecallerpy@1.0.2](https://pypi.org/project/truecallerpy/)

**Comment by VICIWUOHA** [comment]
Good to Know that this has been fixed. @sumithemmadi  💯 , however, you seem to be **overwriting all the files/ the entire repo** on every new fix/commit. as i can't seem to see any history for the changelogs. Suggesting you make changes by opening PR's on this same repo maybe via a different branch and merging same into the main branch.

**Comment by sumithemmadi** [comment]
@VICIWUOHA  Yes i know, but my intention is to continue updating the changelogs after resolving the issues associated with error code 426. That's why I'm doing a force push, as I don't think the old code is needed anymore. but i will manage to do it  next versions.
