### ISSUE TITLE
Functions not working

### ISSUE THREAD

**Issue by eliconn** [sumithemmadi/truecallerpy#21]
When trying to import a function, it gives an error that the same function cannot be imported
`cannot import name 'login' from 'truecallerpy'`

The documents should be changed from:

To log in to your Truecaller account, use the following command:

`truecallerpy login`

to
```

To log in to your Truecaller account, use the following command:

`truecallerpy --login`
```

**Comment by sumithemmadi** [comment]
Use [truecallerjs@1.0.2](https://pypi.org/project/truecallerpy/)
