### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by SammonBabu** [sumithemmadi/truecallerpy#22]
After the package updation, I am getting following error.
```
{
  "status_code": 426,
  "error": "HTTP Error",
  "message": "An HTTP error occurred: Client error '426 unknown' for url 'https://search5-noneu.truecaller.com/v2/search?q=9876543210&countryCode=91&type=4&locAddr=&placement=SEARCHRESULTS%2CHISTORY%2CDETAILS&encoding=json'\nFor more information check: https://httpstatuses.com/426"
}
```

**Comment by sumithemmadi** [comment]
which country phone number are you using ?
which version of truecallerpy ?

**Comment by SammonBabu** [comment]
I am now using latest version.
truecallerpy==1.0.2
I checked with Indian numbers as well as US numbers.
Both are not working.
When I was using truecallerpy==0.1.2, it was working fine, but that version unavailable now.

**Comment by sumithemmadi** [comment]
I have changed the whole code. See this

https://github.com/sumithemmadi/truecallerpy#login-function

If you thing older version is working for you.

Download version 0.1.2 from here
https://github.com/sumithemmadi/truecallerpy/releases/tag/v0.1.2

Download and unzip the file. Then go to unzipped directory and run p`ip
install .`

**Comment by sumithemmadi** [comment]
I have changed the whole code. See this

https://github.com/sumithemmadi/truecallerpy#login-function

If you think older version is working for you.

Download version 0.1.2 from here
https://github.com/sumithemmadi/truecallerpy/releases/tag/v0.1.2

Download and unzip the file.
 Then go to unzipped directory and run 

`pip install .`

**Comment by SammonBabu** [comment]
I am using the same way mentioned in this code :
[Phone Number Search](https://github.com/sumithemmadi/truecallerpy#phone-number-search)
I don't know why suddenly happened.
I was using the previous package in Docker, and now that version is not found on pypi.org.
That was causing error, That's why I updated to latest package and changed the code and now I am getting this error.

**Comment by anaschaudhary33** [comment]
I am also getting the same error

**Comment by SammonBabu** [comment]
The issue was with the installation id, After I changed the installation id and updated to the latest version, the issue seems resolved.
