### ISSUE TITLE
status_code: 426

### ISSUE THREAD

**Issue by Destroyer40** [sumithemmadi/truecallerpy#25]
{
  "status_code": 426,
  "error": "HTTP Error",
  "message": "An HTTP error occurred: Client error '426 unknown' for url 'https://search5-noneu.truecaller.com/v2/search?q=123456789&countryCode=91&type=4&locAddr=&placement=SEARCHRESULTS%2CHISTORY%2CDETAILS&encoding=json'\nFor more information check: https://httpstatuses.com/426"
}

**Comment by Destroyer40** [comment]
A 426 status code is caused when a client is attempting to upgrade a connection to a newer version of a protocol, but the server is refusing to do so.

This can happen for several reasons, including:

Incompatibility between the client and server versions of the protocol.

The server may not support the requested version of the protocol.

The server may be configured to only allow certain versions of the protocol to be used.

The server may be experiencing technical issues or undergoing maintenance that prevents it from upgrading the connection.

**Comment by Ergokron** [comment]
Now I have encountered this error, I do not know what to do. If you have solved this problem, describe the solution to the problem

**Comment by Ergokron** [comment]
the library worked for about 2 weeks, and then it started to give an error
