### ISSUE TITLE
Error: too many requests

### ISSUE THREAD

**Issue by shimuldn** [sumithemmadi/truecallerpy#5]
Few requests worked, but now getting this error:

Edit: Created new truecaller account working again. So the previous account got banned? Previous account working fine on android truecaller app.

```
 truecallerpy -s +912242207777
Traceback (most recent call last):
  File "/usr/local/bin/truecallerpy", line 8, in <module>
    sys.exit(ExecuteTrurcallerPy())
  File "/usr/local/lib/python3.8/dist-packages/truecallerpy/__init__.py", line 217, in ExecuteTrurcallerPy
    truecallerpy_search_phonenumber(config)
  File "/usr/local/lib/python3.8/dist-packages/truecallerpy/__init__.py", line 132, in truecallerpy_search_phonenumber
    jsonInfo = search_phonenumber(getNumber(
  File "/usr/local/lib/python3.8/dist-packages/truecallerpy/__init__.py", line 105, in search_phonenumber
    if req.json().get('status'):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sumithemmadi** [comment]
send me which version of package you are using
```
~$ truecallerpy -v
```
if the version is not showing update to latest version and try , if version shows just post here i will check

**Comment by shimuldn** [comment]
truecallerpy -v

    truecallerpy
    Version     : 0.0.12
    Summary     : A package to find phone number details
    Home-page   : https://github.com/sumithemmadi/truecallerpy
    Author      : Sumith Emmadi
    Author-email: sumithemmadi244@gmail.com
    License     : MIT

**Comment by shimuldn** [comment]
So there is a rate limit for sure. Tried another number 10-20 times! Getting the same error!
Tried to log in again with `truecallerpy -login`  error is `Phone number limit reached`

**Comment by sumithemmadi** [comment]
Yes, there is rate limit . Coming to your problem you got a *JSONDecodeError*, the JSONDecodeError is raised when the response object from Truecaller cannot be converted to JSON.
Maybe it is empty or The response is not a json.

If you want to know what the exact error that you are getting.
Open this file with you favorite text editor

```
vim  `python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))"`/truecallerpy/__init__.py
```
If you are using vscode
```
code  `python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))"`/truecallerpy/__init__.py
```
And add  `print(req.text)` after line number 104 and save it.
Then try to run you will get same error with response if truecaller , paste the output at here i will check it.
Btw which operating system are you using ?

**Comment by shimuldn** [comment]
Error code 429
Error Message `too many requests`

**Comment by sumithemmadi** [comment]
fixed in https://github.com/sumithemmadi/truecallerpy/compare/v0.0.12...v0.0.13
