### ISSUE TITLE
Account got blocked instantly

### ISSUE THREAD

**Issue by shimuldn** [sumithemmadi/truecallerpy#7]
Using `truecallerpy --login` account got blocked after verification sms. Can log in again after few days but result same.
Is this end of the story?

```
{
    "status": 2,
    "message": "Verified",
    "installationId": "",
    "ttl": 259200,
    "userId": ,
    "suspended": true,
    "phones": [
        {
            "phoneNumber": ,
            "countryCode": "",
            "priority": 1
        }
    ]
}
```

**Comment by sumithemmadi** [comment]
**Arey you still able to Login in truecaller in truecaller app ?**
> if you can login to truecaller successfully then try this

   1. On Truecaller Android, tap on the 3 line menu on top left then click on `setting's`.
   2. Tap on `Privacy Center` and then click on `Download my data`.
   3. Now a json file is downloaded. 
   4. Save the json file on your PC at any location e.g /home/HP/1234567890-99123456789.json
   5. On you terminal or command prompt enter below command.
   ```
   ~$ truecallerpy --login -f /home/HP/1234567890-99123456789.json
   ```
   6. Now you are successfully logged in.

**If you are not able to Login to truecaller app.**
Then raise a ticket  to truecaller https://support.truecaller.com/support/tickets/new about your problem.

**Comment by SammonBabu** [comment]
The new version does not support to login from the json file. Is it possible to login from the json file now?
